### ISSUE TITLE
ファイルI/Oを取り扱う処理と、encode/decode処理を分離する

### ISSUE THREAD

**Issue by k16em** [inukai-norio/cece#33]
関連: #13 

## なぜ
暗号/復号化のユニットテストを作成しようとしたが、暗号/復号化の処理にファイルのI/Oを取り扱う処理も書かれており、テストが作成しづらい。
https://github.com/inukai-norio/cece/blob/0ef8041469e3175f1409e7a39debffa898443f49/src/main.rs#L18-L21

## どうしたいか
functionの関心を分離したい。
このように分割し、現状のencode/decodeのループ内にある処理を外に出せばよいはず。

```
fn encode(infile: &str, outfile: &str, passwd: &str, algo: &str, info: &str)
fn encode_strings(input: &str, passwd: &str, algo: &str, info: &str)
fn decode(infile: &str, outfile: &str, passwd: &str) 
fn decode_strings(input: &str, passwd: &str) 
```

## どうなるか
- 暗号/復号化のユニットテスト作成時にファイルI/Oの考慮がいらなくなる
  - テストではファイルではなく文字列を渡せばよくなる

**Comment by inukai-norio** [comment]
👍 
いったん動くことを優先して、関数の分割がおざなりになっているので、是非ともやっていただきたいです。
